Some small updates to FH scenario rules
Lurkars/gloomhavensecretariat pull request #289
Opened 2023-05-11 10:16 UTC by TheSquinter

Some tidying up of special rules and boss abilities

2023-05-13 20:26 UTC, Lurkars requested changes
Have added some questions...

2023-05-14 04:05 UTC, TheSquinter commented on data/fh/scenarios/103.json
> -      ]
I thought it looked too congested to happen each round, especially on mobile and when not all monsters would be needed.
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/124784924/6d583d55-f3fd-46c8-b0f5-29487ad3dcca)

This now reminds them and players can manually spawn the monsters as needed.

2023-05-14 04:06 UTC, TheSquinter commented on data/fh/sections/97-3.json
> -    },
It's already added automatically via permanent condition muddle to all characters from the previous section.

2023-05-14 04:09 UTC, TheSquinter commented on data/fh/sections/167-1.json
> -  ],
The objectives were already defined in parent 54 and have the tags added there for the `rules` of opening sections when X objectives are killed.

2023-05-14 06:32 UTC, merged