fix: #51 trapper perks
Lurkars/gloomhavensecretariat pull request #53
Opened 2022-12-19 23:28 UTC by Viou

I'm not sure about some of the text for the traps; e.g. should I be using:

-  %game.action.attack% 1
-  +1 %game.action.attack% 
-  %game.damage:1% 

I ended up using %game.action.attack% 1
I'm also not sure what the value of value property should be for custom attackModifier.effects.

Lastly, I noticed the perks for this one are so long that you can't read the last one. So heads up, that might need a style fix.

2022-12-20 06:36 UTC, Lurkars commented
Sadly I don't know the real design. But anyways, the value should be what's written on the card. The custom field should only be used, when there is a short cut for the value and a longer text on the perks. For now your have mostly used custom everywhere and for example the heal 2 trap card just have a value of "+2 heal", which will never indicate in the card itself, that you need to create a trap instead of performing a heal action. For now I would asked you to just use the value field for all and ignore the custom field. I will polish this later, when I got a view on the actual cards and adjusting design. For now it will work better when the whole text is also visible on the card!

2022-12-20 15:50 UTC, Viou commented
I'm not sure what you mean by removing "custom". For custom effects, I've moved "hint" into "value". If that's not what you're looking for, could you provide an example of one of these changes? 

This is what the change looks like locally
<details>
  <summary>Spoiler</summary>
  <img width="229" alt="image" src="https://user-images.githubusercontent.com/11701911/208708316-47315d05-56f6-4e8d-a372-dc0f02044473.png">
</details>

2022-12-20 23:30 UTC, Viou commented
Alright, I've cleaned up the PR

2022-12-21 07:11 UTC, Lurkars requested changes

2022-12-21 07:11 UTC, Lurkars commented on data/fh/character/trap.json
> +                "value": "Create one %game.action.attack% 1 trap in an empty hex adjacent to the target"
Replace `%game.action.attack% 1` with `%game.damage:1%`

2022-12-21 07:11 UTC, Lurkars commented on data/fh/character/trap.json
> +      "custom": "Whenever you long rest, you may create one %game.action.attack% 1 trap in an adjacent empty hex"
Replace `%game.action.attack% 1` with `%game.damage:1%`

2022-12-21 07:11 UTC, Lurkars commented on data/fh/character/trap.json
> +      "custom": "At the start of each scenario, you may create one %game.action.attack% 2 trap in an adjacent empty hex"
Replace `%game.action.attack% 2` with `%game.damage:2%`

2022-12-22 03:03 UTC, Viou commented
Updated!

2022-12-22 04:54 UTC, Lurkars approved these changes

2022-12-22 04:54 UTC, merged